export const data = [
  {
    driver: "Bianca Lopes",
    infractionValue: 220,
    infractions: 7,
    active: true,
    lastInfraction: new Date("2024-08-12"),
  },
  {
    driver: "Marcelo da Silva",
    infractionValue: 1220,
    infractions: 85,
    active: true,
    lastInfraction: new Date("2024-06-01"),
  },
  {
    driver: "Joana Pereira",
    infractionValue: 540,
    infractions: 12,
    active: false,
    lastInfraction: new Date("2024-11-02"),
  },
  {
    driver: "Carlos Andrade",
    infractionValue: 3100,
    infractions: 212,
    active: true,
    lastInfraction: new Date("2024-11-16"),
  },
  {
    driver: "Ana Monteiro",
    infractionValue: 180,
    infractions: 4,
    active: false,
    lastInfraction: new Date("2024-02-21"),
  },
  {
    driver: "Rodrigo Nascimento Rivaldo Jesus Amado Batista",
    infractionValue: 800,
    infractions: 34,
    active: true,
    lastInfraction: new Date("2024-10-03"),
  },
  {
    driver: "Juliana Borges",
    infractionValue: 1420,
    infractions: 67,
    active: true,
    lastInfraction: new Date("2024-11-18"),
  },
  {
    driver: "Vitor Fernandes",
    infractionValue: 350,
    infractions: 11,
    active: false,
    lastInfraction: new Date("2024-05-11"),
  },
  {
    driver: "Larissa Martins",
    infractionValue: 2900,
    infractions: 154,
    active: true,
    lastInfraction: new Date("2024-08-29"),
  },
];
